pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build') {
            tools {
                        maven 'maven'
                 }
            steps {
                sh 'mvn -B -DskipTests clean package'
                // List the contents of target to verify the JAR is built
                sh 'ls -lh target'
            }
        }
        stage('Test') {
            tools {
                        maven 'maven'
                 }
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') { 
            tools {
                jdk 'java'
            }
            steps {
                 // Check if the JAR exists before running deliver.sh
                sh 'NAME=$(mvn -q -DforceStdout help:evaluate -Dexpression=project.name); VERSION=$(mvn -q -DforceStdout help:evaluate -Dexpression=project.version); JAR="target/${NAME}-${VERSION}.jar"; [ -f "$JAR" ] && echo "JAR found: $JAR" || { echo "JAR missing!"; ls -lh target; exit 1; }'
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
